### ISSUE TITLE
Make lockbox configurable using a YAML/TOML/JSON config file

### ISSUE THREAD

**Issue by SonuBardai** [SonuBardai/lockbox#27]
Lockbox should be configurable. In the main function, look for a config file in a `$HOME/.lockbox/config.yaml` or `$HOME/lockbox.toml`, etc. config file; read & parse the config file; use the configurations during the run. The format of the config file needs to be decided, it can be yaml / toml / json. Some example config options could look like this

```yaml
master_password:
    visibility: [ hidden | asterisk | visible ]     # visibility when typing in
    character: "*"  # character to be used when set to asterisk
password:
    visibility: [ hidden | asterisk | visible ]     # visibility when typing in
    character: "*"             # character to be used when set to asterisk
    always_generate: false     # Always use the --generate flag for random passwords
password_store:
    storage_type: [ local | s3 ]
    credentials: ~/.aws/config
```
